language: php

php:
  - 5.3

install:
  - composer install
  - composer install --dev
  - composer update

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --bootstrap ef-test/Tests/bootstrap.php ef-test/Tests

after_script:
  - php vendor/bin/coveralls -v