language: php

php:
  - 5.3

before_script:
 - wget http://getcomposer.org/composer.phar
 - composer install --dev --no-interaction

install:
  composer install

script:
  mkdir -p build/logs
  phpunit --coverage-clover build/logs/clover.xml --bootstrap ef-test/Tests/bootstrap.php ef-test/Tests

after_script:
 - php vendor/bin/coveralls -v